apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: zerotrust
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command:
            - cloudflared
            - --protocol
            - http2
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - {{ .Values.token }}
